name: snvCalling
channels:
  - biobuilds
  - anaconda
  - bioconda
  - defaults
dependencies:
  - gcc_linux-64=7.3.0=h553295d_15
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - fasta=36.3.8e=1
  - argh=0.26.1=py27_0
  - bcbio-nextgen=1.1.6a=py27_0
  - bcftools=1.9=ha228f0b_4
  - bedtools=2.29.2=hc088bd4_0
  - bioblend=0.12.0=py_0
  - biopython=1.70=np112py27_1
  - bowtie2=2.3.5.1=py27he513fc3_0
  - bwa=0.7.17=hed695b0_7
  - cyvcf2=0.11.6=py27hce88a48_0
  - dnapi=1.1=py_3
  - fadapa=0.3.1=py_1
  - fastq-pair=1.0=hf484d3e_0
  - fastqc=0.11.9=0
  - freebayes=1.3.2=py27hc088bd4_0
  - gatk=3.8=7
  - geneimpacts=0.3.7=py_1
  - gffutils=0.9=py_1
  - htslib=1.9=ha228f0b_7
  - ipython-cluster-helper=0.6.4=py_0
  - libdeflate=1.0=h14c3975_1
  - logbook=1.4.3=py27h14c3975_0
  - mirtop=0.4.23=py_0
  - mmtf-python=1.0.2=py27_0
  - multiqc=0.9.1a0=py27_4
  - netifaces=0.10.4=py27_1
  - parallel=20160622=1
  - perl-threaded=5.26.0=0
  - picard=2.23.0=0
  - pybedtools=0.8.1=py27he513fc3_0
  - pyfaidx=0.5.8=py_1
  - pysam=0.15.3=py27hda2845c_1
  - pyvcf=0.6.8=py27_0
  - requests-toolbelt=0.5.0=py27_0
  - samtools=1.9=h10a08f8_12
  - scala=2.11.8=1
  - seqcluster=1.2.7=py_0
  - simplejson=3.8.1=py27_0
  - snpsift=4.3.1t=2
  - trimmomatic=0.39=1
  - vardict=2019.06.04=pl526_0
  - vardict-java=1.7.0=0
  - vcflib=1.0.0_rc2=h56106d0_2
  - vcftools=0.1.16=he860b03_3
  - viennarna=2.4.14=py27h8b12597_0
  - yamllint=1.2.1=py27_0
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=anacondar_1
  - argcomplete=1.11.1=py_1
  - arrow=0.13.1=py27_0
  - asn1crypto=1.3.0=py27_0
  - atomicwrites=1.4.0=py_0
  - attrs=19.3.0=py_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports.shutil_get_terminal_size=1.0.0=py27_2
  - backports_abc=0.5=py_0
  - beautifulsoup4=4.8.2=py27_0
  - binutils_impl_linux-64=2.33.1=he6710b0_7
  - binutils_linux-64=2.33.1=h9595d00_15
  - blas=1.0=mkl
  - boto=2.49.0=py27_0
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py27_0
  - cffi=1.13.2=py27h2e261b9_0
  - chardet=3.0.4=py27_1003
  - click=7.1.2=py_0
  - coloredlogs=10.0=py27_0
  - configparser=4.0.2=py27_0
  - contextlib2=0.6.0.post1=py_0
  - coverage=5.0=py27h7b6447c_0
  - cryptography=2.8=py27h1ba5d50_0
  - curl=7.67.0=hbc83047_0
  - cycler=0.10.0=py27_0
  - cython=0.29.14=py27he6710b0_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - distribute=0.6.45=py27_1
  - enum34=1.1.6=py27_1
  - expat=2.2.6=he6710b0_0
  - font-ttf-dejavu-sans-mono=2.37=h6964260_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - funcsigs=1.0.2=py27h83f16ab_0
  - functools32=3.2.3.2=py27_1
  - futures=3.3.0=py27_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_15
  - git=2.23.0=pl526hacde149_0
  - glib=2.63.1=h5a9c865_0
  - graphite2=1.3.13=h23475e2_0
  - gsl=2.4=h14c3975_4
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_15
  - h5py=2.9.0=py27h7918eee_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.4=hb1b8bf9_0
  - humanfriendly=4.18=py27_0
  - icu=58.2=he6710b0_3
  - idna=2.8=py27_0
  - importlib_metadata=1.3.0=py27_0
  - intel-openmp=2019.4=243
  - ipaddress=1.0.23=py_0
  - ipykernel=4.10.0=py27_0
  - ipyparallel=6.2.4=py27_0
  - ipython=5.8.0=py27_0
  - ipython_genutils=0.2.0=py27h89fb69b_0
  - jinja2=2.11.2=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=5.3.4=py27_0
  - jupyter_core=4.6.1=py27_0
  - kiwisolver=1.1.0=py27he6710b0_0
  - krb5=1.16.4=h173b8e3_0
  - libcurl=7.67.0=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.10=he19cac6_1
  - linecache2=1.0.0=py27_0
  - lz4-c=1.9.2=he6710b0_0
  - make=4.2.1=h1bed415_1
  - markupsafe=1.1.1=py27h7b6447c_0
  - matplotlib=2.2.3=py27hb69df0a_0
  - mkl=2018.0.3=1
  - mkl-service=1.1.2=py27h90e4bf4_5
  - mkl_fft=1.0.6=py27h7dd41cf_0
  - mkl_random=1.0.1=py27h4414c95_1
  - mock=3.0.5=py27_0
  - more-itertools=5.0.0=py27_0
  - msgpack-python=0.6.1=py27hfd86e86_1
  - ncurses=6.1=he6710b0_1
  - numpy=1.12.1=py27h9378851_1
  - numpy-base=1.15.0=py27h1793315_0
  - olefile=0.46=py_0
  - openjdk=8.0.152=h7b6447c_3
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.3=py_0
  - pandas=0.24.2=py27he6710b0_0
  - pango=1.42.4=h049681c_0
  - pathlib2=2.3.5=py27_0
  - patsy=0.5.1=py27_0
  - pcre=8.43=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - pexpect=4.7.0=py27_0
  - pickleshare=0.7.5=py27_0
  - pillow=6.2.1=py27h34e0f95_0
  - pip=19.3.1=py27_0
  - pixman=0.38.0=h7b6447c_0
  - pluggy=0.13.1=py27_0
  - progressbar2=3.37.1=py27_0
  - prompt_toolkit=1.0.15=py27_0
  - psutil=5.6.7=py27h7b6447c_0
  - ptyprocess=0.6.0=py27_0
  - py=1.8.1=py_0
  - pycparser=2.20=py_0
  - pycrypto=2.6.1=py27h14c3975_9
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py27_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py27h05f1152_2
  - pysocks=1.7.1=py27_0
  - pytest=4.6.2=py27_0
  - pytest-cov=2.9.0=py_0
  - pytest-mock=2.0.0=py_0
  - pytest-runner=5.2=py_0
  - python=2.7.17=h9bab390_0
  - python-dateutil=2.8.1=py_0
  - python-utils=2.3.0=py27_0
  - pytz=2020.1=py_0
  - pyyaml=5.2=py27h7b6447c_0
  - pyzmq=18.1.0=py27he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-base=3.6.1=h9bb98a2_1
  - r-bitops=1.0_6=r36h96ca727_4
  - r-catools=1.17.1.2=r36h29659fb_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-colorspace=1.4_1=r36h96ca727_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-dichromat=2.0_0=r36h6115d3f_4
  - r-digest=0.6.18=r36h96ca727_0
  - r-fansi=0.4.0=r36h96ca727_0
  - r-gdata=2.18.0=r36h6115d3f_0
  - r-ggplot2=3.1.1=r36h6115d3f_0
  - r-glue=1.3.1=r36h96ca727_0
  - r-gplots=3.0.1.1=r36h6115d3f_0
  - r-gsalib=2.1=r36h6115d3f_0
  - r-gtable=0.3.0=r36h6115d3f_0
  - r-gtools=3.8.1=r36h96ca727_0
  - r-kernsmooth=2.23_15=r36ha65eedd_4
  - r-labeling=0.3=r36h6115d3f_4
  - r-lattice=0.20_38=r36h96ca727_0
  - r-lazyeval=0.2.2=r36h96ca727_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-mass=7.3_51.3=r36h96ca727_0
  - r-matrix=1.2_17=r36h96ca727_0
  - r-mgcv=1.8_28=r36h96ca727_0
  - r-munsell=0.5.0=r36h6115d3f_0
  - r-nlme=3.1_139=r36ha65eedd_0
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-plyr=1.8.4=r36h29659fb_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h29659fb_0
  - r-reshape=0.8.8=r36h6115d3f_0
  - r-reshape2=1.4.3=r36h29659fb_0
  - r-rlang=0.3.4=r36h96ca727_0
  - r-scales=1.0.0=r36h29659fb_0
  - r-stringi=1.4.3=r36h29659fb_0
  - r-stringr=1.4.0=r36h6115d3f_0
  - r-tibble=2.1.1=r36h96ca727_0
  - r-utf8=1.1.4=r36h96ca727_0
  - r-viridislite=0.3.0=r36h6115d3f_0
  - r-withr=2.1.2=r36h6115d3f_0
  - readline=7.0=h7b6447c_5
  - reportlab=3.5.26=py27he686d34_0
  - requests=2.22.0=py27_1
  - scandir=1.10.0=py27h7b6447c_0
  - scikit-learn=0.20.1=py27h4989274_0
  - scipy=1.1.0=py27hd20e5f9_0
  - seaborn=0.9.0=pyh91ea838_1
  - setuptools=44.0.0=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27_0
  - sip=4.19.8=py27hf484d3e_0
  - six=1.15.0=py_0
  - soupsieve=1.9.5=py27_0
  - sqlite=3.31.1=h7b6447c_0
  - statsmodels=0.10.1=py27hdd07704_0
  - subprocess32=3.5.4=py27h7b6447c_0
  - system=5.8=2
  - tabulate=0.8.3=py27_0
  - tbb=2020.0=hfd86e86_0
  - tbb4py=2019.8=py27hfd86e86_0
  - tk=8.6.8=hbc83047_0
  - tktable=2.10=h14c3975_0
  - toolz=0.10.0=py_0
  - tornado=5.1.1=py27h7b6447c_0
  - traceback2=1.4.0=py27_0
  - traitlets=4.3.3=py27_0
  - unittest2=1.1.0=py27_0
  - urllib3=1.25.7=py27_0
  - wcwidth=0.1.9=py_0
  - wheel=0.33.6=py27_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
prefix: /home/luc32/.conda/envs/snvCalling

